# fly.toml app configuration file generated for cool-shape-1381 on 2023-04-20T19:29:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cool-shape-1381"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
